apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat
  template:
    metadata:
      labels:
        app: tomcat
    spec:
      containers:
        - name: tomcat
          image: 665693299603.dkr.ecr.us-east-1.amazonaws.com/usda_poc:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: root
            - name: MYSQL_DATABASE
              value: testdb1
            - name: MYSQL_USER
              value: testuser
            - name: MYSQL_PASSWORD
              value: root
          ports:
            - containerPort: 8080
        imagePullSecrets:
          - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
