apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonar-data-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: sonar-storage-class
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-01510d730cac18f92::fsap-07a090274f4c87cbe