apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonar-data-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: sonar-storage-class
  resources:
    requests:
      storage: 5Gi